/* global process */
import fs from "node:fs/promises";
import path from "node:path";
import { URL } from "node:url";
import { chromium } from "playwright";
import { JSDOM } from "jsdom";import { Readability } from "@mozilla/readability";import createDOMPurify from "dompurify";import TurndownService from "turndown";
import { allowedHostFor, resolvePublicHost } from "./policy.mjs";

const line = await new Promise((resolve) => { let data="";process.stdin.setEncoding("utf8");process.stdin.on("data",(chunk)=>{data+=chunk;});process.stdin.on("end",()=>resolve(data.trim())); });
const rpc=JSON.parse(line);const params=rpc.params;
if(rpc.method==="browser.login"){
 const sourceUrl=params.url;const target=new URL(sourceUrl);const platform=params.platform;const profile=path.resolve(params.profilePath);await fs.mkdir(profile,{recursive:true});const addresses=await resolvePublicHost(target.hostname);const rules=addresses.map((address)=>`MAP ${target.hostname} ${address}`).join(",");const context=await chromium.launchPersistentContext(profile,{headless:false,acceptDownloads:false,ignoreHTTPSErrors:false,args:["--disable-extensions","--disable-background-networking","--disable-component-update","--disable-sync","--disable-default-apps",`--host-resolver-rules=${rules}`]});try{const page=context.pages()[0]||await context.newPage();page.on("popup",popup=>popup.close());await page.route("**/*",async(route)=>{const requestUrl=new URL(route.request().url());if(!["http:","https:"].includes(requestUrl.protocol)||!allowedHostFor(platform,target.hostname,requestUrl.hostname)){await route.abort("blockedbyclient");return;}try{await resolvePublicHost(requestUrl.hostname);await route.continue();}catch{await route.abort("blockedbyclient");}});await page.goto(sourceUrl,{waitUntil:"domcontentloaded",timeout:45_000});const deadline=Date.now()+Math.min(params.timeoutMs||600_000,600_000);let authenticated=false;while(Date.now()<deadline){if(page.isClosed())break;const text=await page.locator("body").innerText().catch(()=>"");if(text&&!/登录|login required|sign in/i.test(text)){authenticated=true;break;}await page.waitForTimeout(1000);}process.stdout.write(`${JSON.stringify({jsonrpc:"2.0",id:rpc.id,result:{authenticated},error:null})}\n`);}finally{await context.close();}process.exit(0);
}
const sourceUrl=params.input.normalizedLocator||params.input.locator;const target=new URL(sourceUrl);const platform=target.hostname.includes("weixin")?"wechat":target.hostname.includes("zhihu")?"zhihu":target.hostname.includes("bilibili")||target.hostname==="b23.tv"?"bilibili":"generic";
const stagingRoot=path.resolve(params.projectRoot,params.stagingRoot);const profile=path.join(stagingRoot,"browser-profile");await fs.mkdir(profile,{recursive:true});
const targetAddresses=await resolvePublicHost(target.hostname);const resolverRules=targetAddresses.map((address)=>`MAP ${target.hostname} ${address}`).join(",");
const context=await chromium.launchPersistentContext(profile,{headless:true,acceptDownloads:false,ignoreHTTPSErrors:false,args:["--disable-extensions","--disable-background-networking","--disable-component-update","--disable-sync","--disable-default-apps",`--host-resolver-rules=${resolverRules}`]});
try{
 const page=await context.newPage();page.on("popup",(popup)=>popup.close());
 await page.route("**/*",async(route)=>{const requestUrl=new URL(route.request().url());if(!["http:","https:"].includes(requestUrl.protocol)||!allowedHostFor(platform,target.hostname,requestUrl.hostname)){await route.abort("blockedbyclient");return;}try{await resolvePublicHost(requestUrl.hostname);await route.continue();}catch{await route.abort("blockedbyclient");}});
 await page.goto(sourceUrl,{waitUntil:"domcontentloaded",timeout:45_000});await page.waitForTimeout(750);
 const bodyText=await page.locator("body").innerText().catch(()=>"");if(/captcha|challenge|安全验证|环境异常|登录后/i.test(bodyText)){process.stdout.write(`${JSON.stringify({jsonrpc:"2.0",id:rpc.id,result:null,error:{code:-32010,message:"Login or challenge required",data:{code:"IMPORT_WEB_LOGIN_REQUIRED"}}})}\n`);process.exitCode=0;}else{const html=await page.content();const dom=new JSDOM(html,{url:sourceUrl,runScripts:"outside-only",resources:undefined});const article=new Readability(dom.window.document.cloneNode(true)).parse();if(!article?.content||!article.title){throw new Error("dynamic content root missing");}const clean=createDOMPurify(dom.window).sanitize(article.content,{FORBID_TAGS:["script","style","iframe","object","embed","form","template"],FORBID_ATTR:["style"]});const cleanDom=new JSDOM(clean,{url:sourceUrl});let assetIndex=0;for(const image of cleanDom.window.document.querySelectorAll("img")){const raw=image.getAttribute("src")||image.getAttribute("data-src");image.removeAttribute("srcset");image.removeAttribute("data-src");if(!raw){image.remove();continue;}const placeholder=`webasset-${assetIndex++}`;image.setAttribute("src",`asset://${placeholder}`);process.stdout.write(`${JSON.stringify({jsonrpc:"2.0",method:"import.remoteAsset",params:{placeholder,url:new URL(raw,sourceUrl).href,kind:"image"}})}\n`);}const persistedHtml=cleanDom.window.document.body.innerHTML;const markdown=new TurndownService({codeBlockStyle:"fenced",headingStyle:"atx"}).turndown(persistedHtml);await fs.writeFile(path.join(stagingRoot,"candidate.md"),`# ${article.title}\n\n${markdown}\n`);await fs.writeFile(path.join(stagingRoot,"source.html"),persistedHtml);await fs.writeFile(path.join(stagingRoot,"metadata.json"),JSON.stringify({title:article.title,byline:article.byline,publicUrl:sourceUrl}));process.stdout.write(`${JSON.stringify({jsonrpc:"2.0",id:rpc.id,result:{sourceSnapshotPath:"source.html",markdownPath:"candidate.md",assetPaths:[],metadataPath:"metadata.json",title:article.title,textCoverage:1,warnings:[]},error:null})}\n`);}
}finally{await context.close();}
