import { invoke } from "@tauri-apps/api/core";

import type {
  AddImportItemsV2Request,
  AddImportTextV2Request,
  CommitImportSessionRequest,
  CreateImportSessionV2Request,
  GetImportSessionV2Request,
  ImportCompletion,
  ImportItem,
  ImportItemPage,
  ImportMergeContextV2Request,
  ImportSession,
  ImportSessionOverview,
  ListImportSessionItemsV2Request,
  ImportThreeWayMergeContext,
  SetImportItemResolutionV2Request,
  SetImportItemSelectionV2Request,
  SelectImportSubtitleV2Request,
  StageImportManualMergeV2Request,
  StartImportItemsV2Request,
  StartImportBatchV2Request,
  CancelImportItemV2Request,
  CancelImportBatchV2Request,
} from "../types/importV2";
import type {
  AcceptImportScanV2Request,
  AcceptImportScanV2Result,
  AddImportPathsV2Request,
  DiscardImportScanV2Request,
  FileScanResult,
  GetImportScanResultV2Request,
} from "../types/importV2File";
import type {
  AddImportCollectionItemsV2Request,
  AddImportUrlV2Request,
  AuthorizeLocalAsrV2Request,
  AuthorizeLocalOcrV2Request,
  ConfirmRemoteMediaRetentionV2Request,
  DiscoverImportCollectionV2Request,
  ImportCollectionPreview,
  ImportCollectionPage,
  LoadImportCollectionPageV2Request,
  RemoteMediaRetentionPlan,
  RemoteMediaRetentionRequest,
} from "../types/importV2Web";
import type { AgentCandidateActionResult, AgentCandidateView } from "../types/importV2Agent";
import type {
  ActivateImportV2Request,
  ActivationResult,
  GetImportBackendActivationRequest,
  ImportBackendActivation,
} from "../types/importV2Activation";
import type {
  ApplyImportV2MigrationRequest,
  LegacyInventory,
  MigrationApplyTask,
  MigrationPreparation,
  MigrationProjectRequest,
  MigrationStatusSnapshot,
  PlanImportV2MigrationRequest,
  ResumeImportV2MigrationRequest,
  ScanImportV2MigrationRequest,
} from "../types/importV2Migration";
import type { BackendTask } from "../types/task";
import type { ImportV2Api, ImportV2CommandNames } from "../types/importV2Api";
import type {
  ImportFrontendReadiness,
  ImportRestrictedContentStatus,
  ImportHistoryPage,
  ImportPreviewContent,
  ImportWorkbenchPreferences,
  ImportWorkbenchPreferencesRequest,
  GetImportFrontendReadinessV2Request,
  GetImportRestrictedContentStatusV2Request,
  GetImportPreviewContentV2Request,
  ListImportHistoryV2Request,
  AuthorizeImportPrivateTargetV2Request,
  BeginImportLoginV2Request,
  CompleteImportLoginV2Request,
  CompleteImportLoginResult,
  ConnectorSessionRef,
  RevokeImportLoginV2Request,
  SaveImportWorkbenchPreferencesRequest,
  GetImportAsrEnablementPlanV2Request,
  GetImportCapabilityRequirementV2Request,
  ImportAsrEnablementPlan,
  ImportCapabilityRequirement,
  InstallImportCapabilityV2Request,
  StartImportAgentAssistanceV2Request,
} from "../types/importV2Presentation";
import type { AcceptImportAgentCandidateRequest, DiscardImportAgentCandidateRequest, SelectImportAgentCandidateRequest } from "../types/importV2Agent";

const commandNames: ImportV2CommandNames = {
  createSession: "create_import_session_v2",
  getSession: "get_import_session_v2",
  getSessionOverview: "get_import_session_overview_v2",
  listSessionItems: "list_import_session_items_v2",
  startSessionRecovery: "start_import_session_recovery_v2",
  getHistorySession: "get_import_history_session_v2",
  getCompletion: "get_import_completion_v2",
  addItems: "add_import_items_v2",
  addPaths: "start_add_import_paths_v2",
  addText: "add_import_text_v2",
  getScanResult: "get_import_scan_result_v2",
  acceptScan: "accept_import_scan_v2",
  discardScan: "discard_import_scan_v2",
  addUrl: "add_import_url_v2",
  discoverCollection: "discover_import_collection_v2",
  loadCollectionPage: "load_import_collection_page_v2",
  addCollectionItems: "add_import_collection_items_v2",
  getRemoteMediaRetentionPlan: "get_remote_media_retention_plan_v2",
  confirmRemoteMediaRetention: "confirm_remote_media_retention_v2",
  setSelection: "set_import_item_selection_v2",
  selectSubtitle: "select_import_subtitle_v2",
  getMergeContext: "get_import_merge_context_v2",
  setItemResolution: "set_import_item_resolution_v2",
  stageManualMerge: "stage_import_manual_merge_v2",
  startItems: "start_import_items_v2",
  startBatch: "start_import_batch_v2",
  cancelBatch: "cancel_import_batch_v2",
  cancelItem: "cancel_import_item_v2",
  skipItem: "skip_import_item_v2",
  authorizeLocalAsr: "authorize_local_asr_v2",
  authorizeLocalOcr: "authorize_local_ocr_v2",
  confirmSession: "confirm_import_session_v2",
  getPreviewContent: "get_import_preview_content_v2",
  getReadiness: "get_import_frontend_readiness_v2",
  getWorkbenchPreferences: "get_import_workbench_preferences_v2",
  saveWorkbenchPreferences: "save_import_workbench_preferences_v2",
  getRestrictedContentStatus: "get_import_restricted_content_status_v2",
  listHistory: "list_import_history_v2",
  authorizePrivateTarget: "authorize_import_private_target_v2",
  beginLogin: "begin_import_login_v2",
  completeLogin: "complete_import_login_v2",
  revokeLogin: "revoke_import_login_v2",
  getCapabilityRequirement: "get_import_capability_requirement_v2",
  getAsrEnablementPlan: "get_import_asr_enablement_plan_v2",
  installCapability: "install_import_capability_v2",
  startAgentAssistance: "start_import_agent_assistance_v2",
  acceptAgentCandidate: "accept_import_agent_candidate_v2",
  selectAgentCandidate: "select_import_agent_candidate_v2",
  discardAgentCandidate: "discard_import_agent_candidate_v2",
  scanMigration: "scan_import_v2_migration",
  planMigration: "plan_import_v2_migration",
  applyMigration: "apply_import_v2_migration",
  getMigrationStatus: "get_import_v2_migration_status",
  resumeMigration: "resume_import_v2_migration",
  activate: "activate_import_v2",
  getActivation: "get_import_backend_activation",
};

const request = <Response, Payload = unknown>(name: string, value: Payload) =>
  invoke<Response>(name, { request: value });

export const importV2Api: ImportV2Api = {
  commandNames,
  createSession: (value: CreateImportSessionV2Request) => request<ImportSession>(commandNames.createSession, value),
  getSession: (value: GetImportSessionV2Request) => request<ImportSession>(commandNames.getSession, value),
  getSessionOverview: (value: GetImportSessionV2Request) => request<ImportSessionOverview>(commandNames.getSessionOverview, value),
  listSessionItems: (value: ListImportSessionItemsV2Request) => request<ImportItemPage>(commandNames.listSessionItems, value),
  startSessionRecovery: (value: GetImportSessionV2Request) => request<BackendTask>(commandNames.startSessionRecovery, value),
  getHistorySession: (value: GetImportSessionV2Request) => request<ImportSession>(commandNames.getHistorySession, value),
  getCompletion: (value: GetImportSessionV2Request) => request<ImportCompletion | null>(commandNames.getCompletion, value),
  addItems: (value: AddImportItemsV2Request) => request<ImportSession>(commandNames.addItems, value),
  addPaths: (value: AddImportPathsV2Request) => request<BackendTask>(commandNames.addPaths, value),
  addText: (value: AddImportTextV2Request) => request<ImportSession>(commandNames.addText, value),
  getScanResult: (value: GetImportScanResultV2Request) => request<FileScanResult>(commandNames.getScanResult, value),
  acceptScan: (value: AcceptImportScanV2Request) => request<AcceptImportScanV2Result>(commandNames.acceptScan, value),
  discardScan: (value: DiscardImportScanV2Request) => request<FileScanResult>(commandNames.discardScan, value),
  addUrl: (value: AddImportUrlV2Request) => request<ImportSession>(commandNames.addUrl, value),
  discoverCollection: (value: DiscoverImportCollectionV2Request) => request<ImportCollectionPreview | null>(commandNames.discoverCollection, value),
  loadCollectionPage: (value: LoadImportCollectionPageV2Request) => request<ImportCollectionPage>(commandNames.loadCollectionPage, value),
  addCollectionItems: (value: AddImportCollectionItemsV2Request) => request<ImportSession>(commandNames.addCollectionItems, value),
  getRemoteMediaRetentionPlan: (value: RemoteMediaRetentionRequest) => request<RemoteMediaRetentionPlan>(commandNames.getRemoteMediaRetentionPlan, value),
  confirmRemoteMediaRetention: (value: ConfirmRemoteMediaRetentionV2Request) => request<ImportSession>(commandNames.confirmRemoteMediaRetention, value),
  setSelection: (value: SetImportItemSelectionV2Request) => request<ImportSession>(commandNames.setSelection, value),
  selectSubtitle: (value: SelectImportSubtitleV2Request) => request<ImportSession>(commandNames.selectSubtitle, value),
  getMergeContext: (value: ImportMergeContextV2Request) => request<ImportThreeWayMergeContext>(commandNames.getMergeContext, value),
  setItemResolution: (value: SetImportItemResolutionV2Request) => request<ImportItem>(commandNames.setItemResolution, value),
  stageManualMerge: (value: StageImportManualMergeV2Request) => request<ImportItem>(commandNames.stageManualMerge, value),
  startItems: (value: StartImportItemsV2Request) => request<BackendTask[]>(commandNames.startItems, value),
  startBatch: (value: StartImportBatchV2Request) => request<BackendTask>(commandNames.startBatch, value),
  cancelBatch: (value: CancelImportBatchV2Request) => request<BackendTask[]>(commandNames.cancelBatch, value),
  cancelItem: (value: CancelImportItemV2Request) => request<ImportSession>(commandNames.cancelItem, value),
  skipItem: (value: CancelImportItemV2Request) => request<ImportSession>(commandNames.skipItem, value),
  authorizeLocalAsr: (value: AuthorizeLocalAsrV2Request) => request<void>(commandNames.authorizeLocalAsr, value),
  authorizeLocalOcr: (value: AuthorizeLocalOcrV2Request) => request<void>(commandNames.authorizeLocalOcr, value),
  confirmSession: (value: CommitImportSessionRequest) => request<BackendTask>(commandNames.confirmSession, value),
  getPreviewContent: (value: GetImportPreviewContentV2Request) => request<ImportPreviewContent>(commandNames.getPreviewContent, value),
  getReadiness: (value: GetImportFrontendReadinessV2Request) => request<ImportFrontendReadiness>(commandNames.getReadiness, value),
  getWorkbenchPreferences: (value: ImportWorkbenchPreferencesRequest) => request<ImportWorkbenchPreferences>(commandNames.getWorkbenchPreferences, value),
  saveWorkbenchPreferences: (value: SaveImportWorkbenchPreferencesRequest) => request<ImportWorkbenchPreferences>(commandNames.saveWorkbenchPreferences, value),
  getRestrictedContentStatus: (value: GetImportRestrictedContentStatusV2Request) => request<ImportRestrictedContentStatus>(commandNames.getRestrictedContentStatus, value),
  listHistory: (value: ListImportHistoryV2Request) => request<ImportHistoryPage>(commandNames.listHistory, value),
  authorizePrivateTarget: (value: AuthorizeImportPrivateTargetV2Request) => request<string>(commandNames.authorizePrivateTarget, value),
  beginLogin: (value: BeginImportLoginV2Request) => request<ConnectorSessionRef>(commandNames.beginLogin, value),
  completeLogin: (value: CompleteImportLoginV2Request) => request<CompleteImportLoginResult>(commandNames.completeLogin, value),
  revokeLogin: (value: RevokeImportLoginV2Request) => request<void>(commandNames.revokeLogin, value),
  getCapabilityRequirement: (value: GetImportCapabilityRequirementV2Request) => request<ImportCapabilityRequirement>(commandNames.getCapabilityRequirement, value),
  getAsrEnablementPlan: (value: GetImportAsrEnablementPlanV2Request) => request<ImportAsrEnablementPlan>(commandNames.getAsrEnablementPlan, value),
  installCapability: (value: InstallImportCapabilityV2Request) => request<BackendTask>(commandNames.installCapability, value),
  startAgentAssistance: (value: StartImportAgentAssistanceV2Request) => request<BackendTask>(commandNames.startAgentAssistance, value),
  acceptAgentCandidate: (value: AcceptImportAgentCandidateRequest) => request<AgentCandidateView>(commandNames.acceptAgentCandidate, value),
  selectAgentCandidate: (value: SelectImportAgentCandidateRequest) => request<AgentCandidateActionResult>(commandNames.selectAgentCandidate, value),
  discardAgentCandidate: (value: DiscardImportAgentCandidateRequest) => request<AgentCandidateActionResult>(commandNames.discardAgentCandidate, value),
  scanMigration: (value: ScanImportV2MigrationRequest) => request<LegacyInventory>(commandNames.scanMigration, value),
  planMigration: (value: PlanImportV2MigrationRequest) => request<MigrationPreparation>(commandNames.planMigration, value),
  applyMigration: (value: ApplyImportV2MigrationRequest) => request<MigrationApplyTask>(commandNames.applyMigration, value),
  getMigrationStatus: (value: MigrationProjectRequest) => request<MigrationStatusSnapshot>(commandNames.getMigrationStatus, value),
  resumeMigration: (value: ResumeImportV2MigrationRequest) => request<MigrationApplyTask>(commandNames.resumeMigration, value),
  activate: (value: ActivateImportV2Request) => request<ActivationResult>(commandNames.activate, value),
  getActivation: (value: GetImportBackendActivationRequest) => request<ImportBackendActivation | null>(commandNames.getActivation, value),
};
