import { invoke } from "@tauri-apps/api/core";

import type {
  AddImportItemsV2Request,
  CommitImportSessionRequest,
  CreateImportSessionV2Request,
  GetImportSessionV2Request,
  ImportSession,
  SetImportItemSelectionV2Request,
  StartImportItemsV2Request,
} from "../types/importV2";
import type { AddImportPathsV2Request, FileScanResult, GetImportScanResultV2Request } from "../types/importV2File";
import type { AddImportUrlV2Request } from "../types/importV2Web";
import type { AgentCandidateActionResult, AgentCandidateView, AgentAssistancePolicy, AgentSendScope } from "../types/importV2Agent";
import type {
  ActivateImportV2Request,
  ActivationResult,
  GetImportBackendActivationRequest,
  ImportBackendActivation,
} from "../types/importV2Activation";
import type {
  ApplyImportV2MigrationRequest,
  LegacyInventory,
  MigrationApplyTask,
  MigrationPlan,
  MigrationProjectRequest,
  MigrationStatusSnapshot,
  PlanImportV2MigrationRequest,
  ResumeImportV2MigrationRequest,
  ScanImportV2MigrationRequest,
} from "../types/importV2Migration";
import type { BackendTask } from "../types/task";
import type {
  ImportV2Api,
  ImportV2CommandNames,
  ImportFrontendReadiness,
  ImportHistoryPage,
  ImportPreviewContent,
  GetImportFrontendReadinessV2Request,
  GetImportPreviewContentV2Request,
  ListImportHistoryV2Request,
  AuthorizeImportPrivateTargetV2Request,
  BeginImportLoginV2Request,
  CompleteImportLoginV2Request,
  ConnectorSessionRef,
  RevokeImportLoginV2Request,
  GetImportCapabilityRequirementV2Request,
  ImportCapabilityRequirement,
  InstallImportCapabilityV2Request,
  GetImportAgentPolicyV2Request,
  SetImportAgentPolicyV2Request,
  StartImportAgentAssistanceV2Request,
  PreviewImportByokScopeV2Request,
  ApproveImportByokAssistanceV2Request,
} from "../types/importV2Presentation";
import type { AcceptImportAgentCandidateRequest, DiscardImportAgentCandidateRequest, SelectImportAgentCandidateRequest } from "../types/importV2Agent";

const commandNames: ImportV2CommandNames = {
  createSession: "create_import_session_v2",
  getSession: "get_import_session_v2",
  addItems: "add_import_items_v2",
  addPaths: "start_add_import_paths_v2",
  getScanResult: "get_import_scan_result_v2",
  addUrl: "add_import_url_v2",
  setSelection: "set_import_item_selection_v2",
  startItems: "start_import_items_v2",
  confirmSession: "confirm_import_session_v2",
  getPreviewContent: "get_import_preview_content_v2",
  getReadiness: "get_import_frontend_readiness_v2",
  listHistory: "list_import_history_v2",
  authorizePrivateTarget: "authorize_import_private_target_v2",
  beginLogin: "begin_import_login_v2",
  completeLogin: "complete_import_login_v2",
  revokeLogin: "revoke_import_login_v2",
  getCapabilityRequirement: "get_import_capability_requirement_v2",
  installCapability: "install_import_capability_v2",
  getAgentPolicy: "get_import_agent_policy_v2",
  setAgentPolicy: "set_import_agent_policy_v2",
  startAgentAssistance: "start_import_agent_assistance_v2",
  previewByokScope: "preview_import_byok_scope_v2",
  approveByokAssistance: "approve_import_byok_assistance_v2",
  acceptAgentCandidate: "accept_import_agent_candidate_v2",
  selectAgentCandidate: "select_import_agent_candidate_v2",
  discardAgentCandidate: "discard_import_agent_candidate_v2",
  scanMigration: "scan_import_v2_migration",
  planMigration: "plan_import_v2_migration",
  applyMigration: "apply_import_v2_migration",
  getMigrationStatus: "get_import_v2_migration_status",
  resumeMigration: "resume_import_v2_migration",
  activate: "activate_import_v2",
  getActivation: "get_import_backend_activation",
};

const request = <Response, Payload = unknown>(name: string, value: Payload) =>
  invoke<Response>(name, { request: value });

export const importV2Api: ImportV2Api = {
  commandNames,
  createSession: (value: CreateImportSessionV2Request) => request<ImportSession>(commandNames.createSession, value),
  getSession: (value: GetImportSessionV2Request) => request<ImportSession>(commandNames.getSession, value),
  addItems: (value: AddImportItemsV2Request) => request<ImportSession>(commandNames.addItems, value),
  addPaths: (value: AddImportPathsV2Request) => request<BackendTask>(commandNames.addPaths, value),
  getScanResult: (value: GetImportScanResultV2Request) => request<FileScanResult>(commandNames.getScanResult, value),
  addUrl: (value: AddImportUrlV2Request) => request<ImportSession>(commandNames.addUrl, value),
  setSelection: (value: SetImportItemSelectionV2Request) => request<ImportSession>(commandNames.setSelection, value),
  startItems: (value: StartImportItemsV2Request) => request<BackendTask[]>(commandNames.startItems, value),
  confirmSession: (value: CommitImportSessionRequest) => request<BackendTask>(commandNames.confirmSession, value),
  getPreviewContent: (value: GetImportPreviewContentV2Request) => request<ImportPreviewContent>(commandNames.getPreviewContent, value),
  getReadiness: (value: GetImportFrontendReadinessV2Request) => request<ImportFrontendReadiness>(commandNames.getReadiness, value),
  listHistory: (value: ListImportHistoryV2Request) => request<ImportHistoryPage>(commandNames.listHistory, value),
  authorizePrivateTarget: (value: AuthorizeImportPrivateTargetV2Request) => request<string>(commandNames.authorizePrivateTarget, value),
  beginLogin: (value: BeginImportLoginV2Request) => request<ConnectorSessionRef>(commandNames.beginLogin, value),
  completeLogin: (value: CompleteImportLoginV2Request) => request<ConnectorSessionRef>(commandNames.completeLogin, value),
  revokeLogin: (value: RevokeImportLoginV2Request) => request<void>(commandNames.revokeLogin, value),
  getCapabilityRequirement: (value: GetImportCapabilityRequirementV2Request) => request<ImportCapabilityRequirement>(commandNames.getCapabilityRequirement, value),
  installCapability: (value: InstallImportCapabilityV2Request) => request<BackendTask>(commandNames.installCapability, value),
  getAgentPolicy: (value: GetImportAgentPolicyV2Request) => request<AgentAssistancePolicy>(commandNames.getAgentPolicy, value),
  setAgentPolicy: (value: SetImportAgentPolicyV2Request) => request<AgentAssistancePolicy>(commandNames.setAgentPolicy, value),
  startAgentAssistance: (value: StartImportAgentAssistanceV2Request) => request<BackendTask>(commandNames.startAgentAssistance, value),
  previewByokScope: (value: PreviewImportByokScopeV2Request) => request<AgentSendScope>(commandNames.previewByokScope, value),
  approveByokAssistance: (value: ApproveImportByokAssistanceV2Request) => request<BackendTask>(commandNames.approveByokAssistance, value),
  acceptAgentCandidate: (value: AcceptImportAgentCandidateRequest) => request<AgentCandidateView>(commandNames.acceptAgentCandidate, value),
  selectAgentCandidate: (value: SelectImportAgentCandidateRequest) => request<AgentCandidateActionResult>(commandNames.selectAgentCandidate, value),
  discardAgentCandidate: (value: DiscardImportAgentCandidateRequest) => request<AgentCandidateActionResult>(commandNames.discardAgentCandidate, value),
  scanMigration: (value: ScanImportV2MigrationRequest) => request<LegacyInventory>(commandNames.scanMigration, value),
  planMigration: (value: PlanImportV2MigrationRequest) => request<MigrationPlan>(commandNames.planMigration, value),
  applyMigration: (value: ApplyImportV2MigrationRequest) => request<MigrationApplyTask>(commandNames.applyMigration, value),
  getMigrationStatus: (value: MigrationProjectRequest) => request<MigrationStatusSnapshot>(commandNames.getMigrationStatus, value),
  resumeMigration: (value: ResumeImportV2MigrationRequest) => request<MigrationApplyTask>(commandNames.resumeMigration, value),
  activate: (value: ActivateImportV2Request) => request<ActivationResult>(commandNames.activate, value),
  getActivation: (value: GetImportBackendActivationRequest) => request<ImportBackendActivation | null>(commandNames.getActivation, value),
};
