pub const PATH_TRAVERSAL: &str = "PATH_TRAVERSAL";
pub const PATH_ABSOLUTE_NOT_ALLOWED: &str = "PATH_ABSOLUTE_NOT_ALLOWED";
pub const PATH_OUTSIDE_PROJECT: &str = "PATH_OUTSIDE_PROJECT";
pub const PATH_INVALID: &str = "PATH_INVALID";
