pub mod activation;
pub mod agent_assistance;
pub mod agent_candidate;
pub mod agent_tools;
pub mod agent_workspace;
pub(crate) mod bilibili;
pub mod capability_embed;
pub mod capability_installer;
pub mod capability_pack;
pub mod capability_runtime;
pub(crate) mod commit;
pub mod connector_session;
pub mod connectors;
pub mod domain_limiter;
pub mod domain_router;
pub mod engine;
pub(crate) mod execution_control;
pub mod file_discovery;
pub mod file_router;
pub mod generic_web_engine;
pub(crate) mod history_reader;
pub mod local_media_engine;
pub mod markdown_normalizer;
pub mod media_router;
pub mod migration;
pub mod native_file_engine;
pub mod ocr_router;
pub mod office_postprocess;
mod orchestrator;
pub mod pack_engine;
pub mod pack_protocol;
pub mod pdf_router;
pub mod platform_network_policy;
pub mod platform_provider;
pub mod quality_gate;
pub(crate) mod redaction;
pub mod remote_media_retention;
pub mod scan_confirmation;
pub(crate) mod session_store;
pub mod source_ai_organize;
pub mod source_finalization;
pub mod source_lifecycle;
pub mod source_registry;
mod structured_extract;
pub mod subtitle;
pub(crate) mod transaction;
pub mod url_policy;
pub mod web_fetch;
pub mod web_target_store;
pub mod wechat_web_engine;

#[cfg(test)]
mod test_support;

pub(crate) use commit::NewSourceTargetReservations;
#[cfg(feature = "gui")]
pub(crate) use orchestrator::{import_batch_operation_session_id, is_import_batch_operation_task};
pub use orchestrator::{routes_for_format, ImportV2Service};
#[cfg(feature = "performance-observers")]
pub use orchestrator::{ImportLockWaitObservation, ImportLockWaitSnapshot};
pub use session_store::{CollectionImportInput, SessionStore};
